#!/bin/sh

cd front # because I was in mono repo and the command had to be launched in front directory. adapt as needed
echo "running tests against your frontend code"
npm run test:ci
if [ $? -eq 0 ]; then
    echo "test ok. running build."
    npm run build
    if [ $? -eq 0 ]; then
        echo "all right. Commiting ongoing."
        exit 0
    fi
fi
echo "your test or build don't pass, there must be a problem in your code."
while true; do
    read -p "Do you wish to commit despite this ?" yn </dev/tty
    case $yn in
        [Yy]* ) exit 0;;
        [Nn]* ) exit 1;;
        * ) echo "Please answer yes or no.";;
    esac
done
exit 1

